kind: ServiceAccount
apiVersion: v1
metadata:
  name: apigee-operator

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: apigee-operator-role
rules:
# - apiGroups: [""]
#   resources: [""]
#   verbs: ["get", "watch", "list", "create", "update", "patch", "delete"] 
- apiGroups: ["oda.tmforum.org"]
  resources: ["exposedapis"]
  verbs: ["get", "watch", "list", "create", "update", "patch", "delete"] 

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: apigee-operator-rolebinding
  namespace: components
subjects:
- kind: ServiceAccount
  name: apigee-operator 
  namespace: default 
roleRef:
  kind: Role 
  name: apigee-operator-role 
  apiGroup: rbac.authorization.k8s.io 
